mySQL:
  database: ""
  host: ""
  user: ""
  password: ""


menu-name: "Display Optimization"

# Entity render distance (server)
server-max-distance: 100

# How often displays around the player are checked in ticks (May affect server load)
update-displays: 3

# Button click sound for the menu
button-sound: BLOCK_NOTE_BLOCK_BANJO

# Block rendering distance in blocks
# slot: 0-8
# Use distance=0 to disable all displays and distance=-1 to show
# Use custom-model-data=0 to prevent the item from receiving its value
# You can add from 1 to 9 buttons
buttons:
  all-off:
    distance: 0
    slot: 1
    item: PAPER
    custom-model-data: 1
    button-name: "all-off"
    button-lore:
      - "all-off"

  distance-low:
    distance: 10
    slot: 3
    item: PAPER
    custom-model-data: 1
    button-name: "Low"
    button-lore:
      - "Low"

  distance-medium:
    distance: 20
    slot: 4
    item: PAPER
    custom-model-data: 1
    button-name: "Medium"
    button-lore:
      - "Medium"

  distance-high:
    distance: 30
    slot: 5
    item: PAPER
    custom-model-data: 1
    button-name: "High"
    button-lore:
      - "High"

  all-on:
    distance: -1
    slot: 7
    item: PAPER
    custom-model-data: 1
    button-name: "all-on"
    button-lore:
      - "all-on"
