name: DisplayRenderDistance
version: '${version}'
main: org.dublimator.displayrenderdistance.DisplayRenderDistance
api-version: 1.20
libraries:
  - com.zaxxer:HikariCP:5.0.1
commands:
  drdistance:
    description: "render"
    usage: "/drdistance [menu, reload]"
  drd:
    usage: "/drd"


permissions:
  drdistance.commands.menu:
    description: "menu"
  drdistance.commands.reload:
    description: "reload"
  drdistance.commands.drd:
    description: "drd"